### ISSUE TITLE
Update non-embedded codelist changelog 

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Extra-Documentation#277]
Need to leave changelog messages (at http://iatistandard.org/upgrades/nonembedded-codelist-changelog/) for:
- [x] [Registration Agencies - Update Descriptions](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/28)
- [x] [Region codelist out of date with DAC CRS source](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/27)
- [x] [Add collaboration type code 7](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/26)
- [x] [Add Finnish Patient and Registration office to Registration agencies](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/25)
- [x] [Add XI-IATI to the OrganisationRegistrationAgency list](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/22)

We also need to update the status of these issues on the support forum (at http://support.iatistandard.org/forums/23076626-Non-embedded-Codelist-Amendments ) to 'Done'

**Comment by stevieflow** [comment]
@caprenter is this not a duplicate of https://github.com/IATI/IATI-Guidance/issues/158 - in that the changelogs are adminsitered in Guidance

Or - are you thinking of this as being updated somewhere else?

**Comment by stevieflow** [comment]
@caprenter I think you mean adding the changelog messages to the relevant individual codelist pages in Extra-Docs, which I can do

However - @Bjwebb - should I branch this off 1.04 or 2.01 ?

**Comment by caprenter** [comment]
Sorry, I meant here: http://iatistandard.org/upgrades/nonembedded-codelist-changelog/

We also need to update the support forum to say these things are done. I am amending the original post to reflect this

**Comment by caprenter** [comment]
@stevieflow - also, you could well be right that this issue is connected to the wrong repository - sorry

**Comment by stevieflow** [comment]
ok - I've added these via https://github.com/IATI/IATI-Guidance/commit/fd8c7122c6e3c26dace093ae555f32d2203ead31 - I think this issue can be closed now
