### ISSUE TITLE
Create Issues for various changes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#380]
A parent element for tracking documentation changes for 2.03.

**Related Schema changes**

- [ ] Update definition: all @xml:lang attributes https://github.com/IATI/IATI-Schemas/issues/336
- [ ] Add new @budget-not-provided attribute for the iati-activity element https://github.com/IATI/IATI-Schemas/issues/337
- [ ] Add new @crs-channel-code attribute for the participating-org element https://github.com/IATI/IATI-Schemas/issues/338
- [ ] Update definition: [reporting/participating/reciever/provider]-org @ref attribute https://github.com/IATI/IATI-Schemas/issues/339
- [ ] Update definition: reporting-org @secondary-reporter attribute https://github.com/IATI/IATI-Schemas/issues/340
- [ ] Update definition: [recipient-region/recipient-region-budget/sector] @vocabulary-uri attribute https://github.com/IATI/IATI-Schemas/issues/341
- [ ] Add new tag element (as a child of the iati-activity element) https://github.com/IATI/IATI-Schemas/issues/342
- [ ] Update definition: recipient-[country|region] / sector @percentage attribute https://github.com/IATI/IATI-Schemas/issues/343
- [ ] Update definition: sector @vocabulary attribute https://github.com/IATI/IATI-Schemas/issues/344
- [ ] Update defintion: [transaction aid-type/default-aid-type] @code attribute https://github.com/IATI/IATI-Schemas/issues/345
- [ ] Add new @vocabulary attributes for elements relating to aid-type https://github.com/IATI/IATI-Schemas/issues/346
- [ ] Update definition: result indicator reference @indicator-uri attribute https://github.com/IATI/IATI-Schemas/issues/347
- [ ] Update definition: capital-spend @percentage attribute https://github.com/IATI/IATI-Schemas/issues/348
- [ ] Update definition: related-activity element https://github.com/IATI/IATI-Schemas/issues/349
- [ ] Update occurrence: default-aid-type element https://github.com/IATI/IATI-Schemas/issues/350
- [ ] Update occurrence: transaction aid-type element https://github.com/IATI/IATI-Schemas/issues/351
- [ ] Update occurrence: result indicator baseline element https://github.com/IATI/IATI-Schemas/issues/352
- [ ] Update occurrence: result indicator @value attributes https://github.com/IATI/IATI-Schemas/issues/353
- [ ] Update occurrence: result indicator period [target|actual] elements https://github.com/IATI/IATI-Schemas/issues/354
- [ ] Add new description element (as a child of all document-link elements) https://github.com/IATI/IATI-Schemas/issues/357
- [ ] Add new document-link element (as a child of various result elements) https://github.com/IATI/IATI-Schemas/issues/359
- [ ] Add new reference element (as a child of the result element) https://github.com/IATI/IATI-Schemas/issues/362
- [ ] Add new @aggregation-status attribute for the indicator element https://github.com/IATI/IATI-Schemas/issues/363
- [ ] Add new @iso-date attribute for the baseline element https://github.com/IATI/IATI-Schemas/issues/364
- [ ] Add new location element (as a child of the baseline element) https://github.com/IATI/IATI-Schemas/issues/365
- [ ] Add new dimension element (as a child of the baseline element) https://github.com/IATI/IATI-Schemas/issues/366

**Related Codelist changes**

- [ ] Update TransactionType Codelist https://github.com/IATI/IATI-Codelists/issues/112
- [ ] Move Codelists from Embedded to Non-Embedded https://github.com/IATI/IATI-Codelists/issues/114

**Related Ruleset changes**

- [ ] Update rule: reference element https://github.com/IATI/IATI-Rulesets/issues/48
