### ISSUE TITLE
Issues to document / log

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#52]
Working list with @iatisupport about issues to specific provide guidance on / flag up
## PUBLISHING RELATED
- [ ] what's the difference between `reporting-org` and Publisher? https://github.com/IATI/IATI-Extra-Documentation/issues/16
- [x] updating activities over time https://github.com/IATI/IATI-Extra-Documentation/issues/46
- [ ] segmenting files - good practice
- [ ] URL construction (data.domain or domain/data etc)
- [ ] Advice for publishers about HTTPS: https://github.com/IATI/IATI-Extra-Documentation/issues/41
- [x] spaces in file names: https://github.com/IATI/IATI-Extra-Documentation/issues/35
- [x] activities in more than one file: https://github.com/IATI/IATI-Extra-Documentation/issues/54
## TECHNICAL RELATED
- [ ] Add general dates guidance: https://github.com/IATI/IATI-Extra-Documentation/issues/38
- [x] Globally unique identifiers: https://github.com/IATI/IATI-Extra-Documentation/issues/45
- [x] structure of identifiers: https://github.com/IATI/IATI-Extra-Documentation/issues/39 
- [x] Capitalisation: https://github.com/IATI/IATI-Extra-Documentation/issues/63
## IN DEPTH 
- [ ] working out percentage splits for sector and countries
- [ ] using RO vocabulary, and pointing people to it
- [ ] using namespace extensions
- [ ] revising budgets  - keep original?
- [ ] capital spend - budget / commitment?
- [ ] country-budget-items - must add up to 100%
- [ ] dealing with imprecise dates
- [ ] language use for freetext / names in elements

**Comment by wendyrogers** [comment]
What do publishers do with their Implementation plans (where is it stored etc.)

**Comment by stevieflow** [comment]
This list is getting longer - propose that we move this and associated Issues into https://github.com/IATI/IATI-Guidance - and out of versioning of the standard

Of course, some guidance might be integral to certain versions of the standard, but it does seem better to manage these issues through Guidance....

**Comment by stevieflow** [comment]
Moved this list over to: https://github.com/IATI/IATI-Guidance/issues/9

If there are any specific 1.04 issues, we can raise Issues accordingly
